pipeline{
    agent any

    tools {
        jdk 'java-17'
        maven 'Maven'
    }

    environment {
        MAVEN_OPTS = '-Dnet.bytebuddy.experimental=true -XX:+EnableDynamicAgentLoading'
    }

    stages{
        stage('Git-Chekout'){
            steps{
                git branch: 'main', url: 'https://github.com/ManojKRISHNAPPA/Calulator-springboot.git'
            }
        }

        stage('Compile'){
            steps{
                sh 'mvn clean compile'
            }
        }

        stage('Test'){
            steps{
                sh 'mvn test'
            }
            post{
                always {
                    junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml'
                }
            }

        }

        stage('Build'){
            steps{
                sh 'mvn clean package -DskipTests=true'
            }
        }

        stage('Publish code coverage report'){
            steps{
                sh 'mvn jacoco:report'
            }
            post {
                always {
                    jacoco execPattern: '**/target/jacoco.exec', classPattern: '**/target/classes', sourcePattern: '**/src/main/java', exclusionPattern: '', changeBuildStatus: true
                }
            }
        }

        // stage('SonarQube - SAST'){
        //     steps{
        //         sh """
        //             mvn sonar:sonar \
        //             -Dsonar.projectKey=devsecops \
        //             -Dsonar.host.url=http://98.82.36.59:9000 \
        //             -Dsonar.login=70d24dd452b85812ebd8d8ebdeab4d40b6b9f892
        //         """
        //     }
        // }

        stage('build && SonarQube analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    // Optionally use a Maven environment you've configured already
        
                        sh 'mvn clean package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar'
                    
                }
            }
        }
        stage("Quality Gate") {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    // Parameter indicates whether to set pipeline to UNSTABLE if Quality Gate fails
                    // true = set pipeline to UNSTABLE, false = don't
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Vulnerability Scan - Docker') {
            steps {
                parallel(
                    "Dependency Scan": {
                        sh "mvn dependency-check:check"
                    },
                    "Trivy Scan": {
                        sh "bash trivy-docker-image-scan.sh"
                    },
                    "OPA Conftest": {
                        sh 'docker run --rm -v $(pwd):/project openpolicyagent/conftest test --policy dockerfile-security.rego Dockerfile'
                    },
                    postBuild: {
                        // Archive the scan report
                        archiveArtifacts artifacts: 'target/dependency-check-report.html', allowEmptyArchive: true
                    }
                )
            }
        }

        stage('Docker Build and Push') {
            steps {
                withDockerRegistry([credentialsId: "docker-hub", url: ""]) {
                sh 'printenv'
                sh 'docker build -t manojkrishnappa/calculator-app:""$GIT_COMMIT"" .'
                sh 'docker push manojkrishnappa/calculator-app:""$GIT_COMMIT""'
                }
            }
        }

    }
}